name: First Workflow # Proivde name of the workflow 
on: workflow_dispatch # type of event to trigger. This can be one or more 
jobs: # can contains multiple jobs 
  first-job: # Defined a custom identifier 
    runs-on: ubuntu-latest # Look for more runner details in Github runners page 
    steps: 
      - name: Print greeting
        run: echo "Hello World!" 
      - name: Print goodbye 
        run: echo "Done - bye!"
